# Generated by Django 5.2.7 on 2025-10-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_id', models.CharField(max_length=20)),
                ('department_hod', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('department_email', models.EmailField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
