# Generated by Django 5.2.7 on 2025-10-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='u9pYzGGmazRwz8kH3mQES7PolSat0keH', editable=False, max_length=32, unique=True),
        ),
    ]
