# Generated by Django 5.2.7 on 2025-10-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='G0uMjxQBUSqF3jHUMwbTUkm7dv9tZyUt', editable=False, max_length=32, unique=True),
        ),
    ]
