# Generated by Django 5.2.7 on 2025-10-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='vlfLVoChw78Tr04B3iB0X9IgEv0ES1Mc', editable=False, max_length=32, unique=True),
        ),
    ]
